BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE T_PAGE ( F_ID NUMBER ( 8, 2 ) PRIMARY KEY NOT NULL, F_NAME VARCHAR2 ( 50 CHAR ), F_DESC VARCHAR2 ( 200 CHAR ), F_DATE_CHANGE TIMESTAMP ( 6 ) DEFAULT SYSDATE )';
  EXECUTE IMMEDIATE 'CREATE TABLE T_PROPERTY ( F_ID NUMBER ( 8, 2 ) PRIMARY KEY NOT NULL, F_NAME VARCHAR2 ( 50 CHAR ), F_DEFAULT_VALUE VARCHAR2 ( 50 CHAR ), F_DEFAULT_LANG_ID NUMBER ( 8, 2 ) )';
  EXECUTE IMMEDIATE 'CREATE TABLE T_PAGE_PROPERTY ( F_ID NUMBER ( 8, 2 ) PRIMARY KEY NOT NULL, F_PAGE_ID NUMBER ( 8, 2 ), F_PROPERTY_ID NUMBER ( 8, 2 ) )';
  EXECUTE IMMEDIATE 'CREATE TABLE T_PAGE_PROPERTY_VALUE ( F_PAGE_PROPERTY_ID NUMBER ( 8, 2 ), F_VALUE VARCHAR2 ( 100 CHAR ), F_LANG_ID NUMBER ( 8, 2 ) )';
  EXECUTE IMMEDIATE 'CREATE TABLE T_LANG_CODE ( F_ID NUMBER ( 8, 2 ) PRIMARY KEY NOT NULL, F_LANG VARCHAR2 ( 2 CHAR ), F_COUNTRY_CODE VARCHAR2 ( 2 CHAR ), F_LANG_CODE VARCHAR2 ( 3 CHAR ) )';

  EXECUTE IMMEDIATE 'CREATE SEQUENCE T_PAGE_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE T_PROPERTY_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE T_PAGE_PROPERTY_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE T_PAGE_PROPERTY_VALUE_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE T_LANG_CODE_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE';

  EXECUTE IMMEDIATE 'ALTER TABLE T_PROPERTY ADD FOREIGN KEY ( F_DEFAULT_LANG_ID ) REFERENCES T_LANG_CODE ( F_ID )';
  EXECUTE IMMEDIATE 'ALTER TABLE T_PAGE_PROPERTY ADD FOREIGN KEY ( F_PAGE_ID ) REFERENCES T_PAGE ( F_ID )';
  EXECUTE IMMEDIATE 'ALTER TABLE T_PAGE_PROPERTY ADD FOREIGN KEY ( F_PROPERTY_ID ) REFERENCES T_PROPERTY ( F_ID )';
  EXECUTE IMMEDIATE 'ALTER TABLE T_PAGE_PROPERTY_VALUE ADD FOREIGN KEY ( F_PAGE_PROPERTY_ID ) REFERENCES T_PAGE_PROPERTY ( F_ID )';
  EXECUTE IMMEDIATE 'ALTER TABLE T_PAGE_PROPERTY_VALUE ADD FOREIGN KEY ( F_LANG_ID ) REFERENCES T_LANG_CODE ( F_ID )';
END;
/